name: ci
on:
  schedule:
    - cron: '0 2 1 * *'
  push:
    branches:
      - master
jobs:
  main:
    runs-on: ubuntu-latest
    env:
      REPO: monstrenyatko/mdns-repeater
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        run: |
          MDNS_REPEATER_VERSION=$(git rev-parse HEAD)
          ./build.sh "$REPO:$(date +%Y%m%d)" "--build-arg MDNS_REPEATER_VERSION=$MDNS_REPEATER_VERSION --push"
          ./build.sh "$REPO:latest" "--build-arg MDNS_REPEATER_VERSION=$MDNS_REPEATER_VERSION --push"
